# Generated by Django 5.2.14 on 2026-05-29 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.IntegerField(unique=True)),
                ('emp_name', models.CharField(max_length=20)),
                ('emp_salary', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
